import { Gem, Gift, ShoppingBag } from "lucide-react";

export const headerLinks = [
  {
    label: 'Pricing',
    route: '/pricing',
  },
  {
    label: 'Product',
    route: '/docs',
  },
  {
    label: 'About',
    route: '/about',
  },
]

export const signUpInitialValues = {
  organization: "",
  firstName: "",
  lastName: "",
  imageUrl: "",
  email: "",
  country: "",
  plan: { 
    type: "",
    paid: false
   },
}

export const plans = {
  free: {
    title: "Free",
    Icon: Gift,
    pricing: 0,
    features: [
      "item Lorem ipsum dolor sit amet.",
      "item Lorem ipsum dolor sit amet.",
      "item Lorem ipsum dolor sit amet.",
    ],
    supress: [
      "item Lorem ipsum dolor sit amet.",
      "item Lorem ipsum dolor sit amet.",
      "item Lorem ipsum dolor sit amet.",
    ]
  },

  basic: {
    title: "Basic",
    Icon: ShoppingBag,
    pricing: 4.99,
    features: [
      "item Lorem ipsum dolor sit amet.",
      "item Lorem ipsum dolor sit amet.",
      "item Lorem ipsum dolor sit amet.",
      "item Lorem ipsum dolor sit amet.",
      "item Lorem ipsum dolor sit amet.",
     
    ],
    supress: [
      "item Lorem ipsum dolor sit amet.",
      
    ]
  },

  premium: {
    title: "Premium",
    Icon: Gem,
    pricing: 5.99,
    features: [
      "item Lorem ipsum dolor sit amet.",
      "item Lorem ipsum dolor sit amet.",
      "item Lorem ipsum dolor sit amet.",
      "item Lorem ipsum dolor sit amet.",
      "item Lorem ipsum dolor sit amet.",
      "item Lorem ipsum dolor sit amet.",
      "item Lorem ipsum dolor sit amet.",
    ],
    supress: [
    ]
  },

}

export const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic (CAR)",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo, Democratic Republic of the",
  "Congo, Republic of the",
  "Costa Rica",
  "Cote d'Ivoire",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini (formerly Swaziland)",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kosovo (not recognized by some countries)",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar (formerly Burma)",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia (formerly Macedonia)",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine State (not recognized by some countries)",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan (officially called the Republic of China)",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste (formerly East Timor)",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates (UAE)",
  "United Kingdom (UK)",
  "United States of America (USA)",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City (Holy See)",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe"
];
